### ISSUE TITLE
default Localize config must set before customer Localize config

### ISSUE THREAD

**Issue by ChinaRedArmy1930** [gin-contrib/i18n#4]
![image](https://user-images.githubusercontent.com/18543437/146909074-1bbb7896-2f65-4da9-9aa2-4e3cd0494f7c.png)
if I set costomer Localize config, this code will set  default Localize config first, so if I don't create "./_example/localize/en.yaml"  it will panic like this:
![image](https://user-images.githubusercontent.com/18543437/146909355-5f4dd35a-603f-486d-902c-9207305a98c1.png)

**Comment by HaiTo** [comment]
@appleboy Could you check it? I facing the same issue. It seems the issue opener created the PR. 
Thank you.

**Comment by bos-hieu** [comment]
@ChinaRedArmy1930 @HaiTo  I updated the constructor https://github.com/gin-contrib/i18n/pull/6/files. I hope that this can resolve your issue.

**Comment by shuntagami** [comment]
@bos-hieu Thank you for your contribution. 
@appleboy This issue seemed to be resolved by https://github.com/gin-contrib/i18n/pull/6

**Comment by appleboy** [comment]
see https://github.com/gin-contrib/i18n/releases/tag/v0.0.1
