### ISSUE TITLE
Override default config when using WithGetLngHandle

### ISSUE THREAD

**Issue by Lord-Y** [gin-contrib/i18n#43]
Hello guys, how can we override default config when using WithGetLngHandle func?
Without it I got the default config and my dummy test is panicking:
```go
panic: open testdata/localize/en.yaml: no such file or directory
```
Sorry to open an issue for that as discussion isn't enable :-)

**Comment by Lord-Y** [comment]
@appleboy @thinkerou any help please?

**Comment by appleboy** [comment]
@Lord-Y PR Welcome :)

**Comment by appleboy** [comment]
try `WithBundle`
